from pathlib import Path

FOLDER_TRIMMING_ILLUMINA = Path('trimming_illumina')
SNAKEFILE_TRIMMING_ILLUMINA = f'{Path(__file__).parent / Path(__file__).stem}.smk'

INPUT_TRIMMOMATIC_FASTQ = FOLDER_TRIMMING_ILLUMINA / 'input' / 'fastq.io'

# Report and summary
OUTPUT_TRIMMING_ILLUMINA_REPORT = FOLDER_TRIMMING_ILLUMINA / 'report' / 'html.io'
OUTPUT_TRIMMING_ILLUMINA_SUMMARY = FOLDER_TRIMMING_ILLUMINA / 'summary' / 'summary_out.tsv'

# Trimming
OUTPUT_TRIMMING_ILLUMINA_READS_PE = FOLDER_TRIMMING_ILLUMINA / 'trimmomatic' / 'fastq-pe.io'
OUTPUT_TRIMMING_ILLUMINA_READS_SE_FWD = FOLDER_TRIMMING_ILLUMINA / 'trimmomatic' / 'fastq-se-forward.io'
OUTPUT_TRIMMING_ILLUMINA_READS_SE_REV = FOLDER_TRIMMING_ILLUMINA / 'trimmomatic' / 'fastq-se-reverse.io'
OUTPUT_TRIMMING_ILLUMINA_INFORMS = FOLDER_TRIMMING_ILLUMINA / 'trimmomatic' / 'informs.io'
OUTPUT_TRIMMING_ILLUMINA_DICT = FOLDER_TRIMMING_ILLUMINA / 'fastq_all.io'

# FastQC
OUTPUT_TRIMMING_ILLUMINA_FASTQC_TXT_PRE = FOLDER_TRIMMING_ILLUMINA / 'fastqc-pre' / 'txt.io'
OUTPUT_TRIMMING_ILLUMINA_FASTQC_HTML_PRE = FOLDER_TRIMMING_ILLUMINA / 'fastqc-pre' / 'html.io'
OUTPUT_TRIMMING_ILLUMINA_FASTQC_TXT_POST = FOLDER_TRIMMING_ILLUMINA / 'fastqc-post' / 'txt.io'
OUTPUT_TRIMMING_ILLUMINA_FASTQC_HTML_POST = FOLDER_TRIMMING_ILLUMINA / 'fastqc-post' / 'html.io'
