from pathlib import Path

FOLDER_TRIMMING_IONTORRENT = Path('trimming_iontorrent')
SNAKEFILE_TRIMMING_IONTORRENT = f'{Path(__file__).parent / Path(__file__).stem}.smk'

# Report and summary
OUTPUT_TRIMMING_IONTORRENT_REPORT = FOLDER_TRIMMING_IONTORRENT / 'report' / 'html.io'
OUTPUT_TRIMMING_IONTORRENT_SUMMARY = FOLDER_TRIMMING_IONTORRENT / 'summary' / 'summary.tsv'

# Trimming
OUTPUT_TRIMMING_IONTORRENT_FASTQ = FOLDER_TRIMMING_IONTORRENT / 'trim_qual' / 'fastq.io'
OUTPUT_TRIMMING_IONTORRENT_DICT = FOLDER_TRIMMING_IONTORRENT / 'fastq_all.io'
OUTPUT_TRIMMING_IONTORRENT_INFORMS_FILT_LEN = FOLDER_TRIMMING_IONTORRENT / 'trim_length' / 'informs.io'
OUTPUT_TRIMMING_IONTORRENT_INFORMS_FILT_QUAL = FOLDER_TRIMMING_IONTORRENT / 'trim_qual' / 'informs.io'

# FastQC
OUTPUT_TRIMMING_IONTORRENT_FASTQC_PRE = FOLDER_TRIMMING_IONTORRENT / 'fastqc-pre' / 'txt.io'
OUTPUT_TRIMMING_IONTORRENT_FASTQC_POST = FOLDER_TRIMMING_IONTORRENT / 'fastqc-post' / 'txt.io'
